# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - echo "$(ls -la)"
          - npm install
          - npm audit fix
          - npm install -g @angular/cli
          - npm run prod-build
          - echo "$(ls -la dist/prod/)"
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.12
            variables:
              USER: 'ramo'
              SERVER: '136.243.169.179'
              EXTRA_ARGS: '-P 22505 -p 1q2w3E'
              REMOTE_PATH: '/var/www/sports/'
              LOCAL_PATH: './dist/prod/*'
              DEBUG: 'true'
